# Generated by Django 2.0.4 on 2018-04-28 04:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('soops', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='soop',
            old_name='content',
            new_name='details',
        ),
        migrations.AddField(
            model_name='soop',
            name='title',
            field=models.CharField(default=django.utils.timezone.now, max_length=300),
            preserve_default=False,
        ),
    ]
