# Generated by Django 2.0.4 on 2018-04-28 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soops', '0002_auto_20180428_0459'),
    ]

    operations = [
        migrations.AddField(
            model_name='soop',
            name='day',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
