# Generated by Django 2.0.4 on 2018-04-30 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soops', '0003_soop_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soop',
            name='day',
            field=models.CharField(max_length=20),
        ),
    ]
