# Generated by Django 2.0.4 on 2018-04-30 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soops', '0004_auto_20180430_0150'),
    ]

    operations = [
        migrations.AddField(
            model_name='soop',
            name='food',
            field=models.CharField(default=['reception'], max_length=500),
            preserve_default=False,
        ),
    ]
