# Generated by Django 2.0.4 on 2018-04-30 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soops', '0006_soop_outurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soop',
            name='outUrl',
            field=models.CharField(max_length=500, unique=True),
        ),
    ]
