# Generated by Django 2.0.4 on 2018-05-06 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soops', '0007_auto_20180430_0245'),
    ]

    operations = [
        migrations.AddField(
            model_name='soop',
            name='when',
            field=models.CharField(max_length=75, null=True),
        ),
    ]
