# Generated by Django 2.0.4 on 2018-05-06 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soops', '0008_soop_when'),
    ]

    operations = [
        migrations.AddField(
            model_name='soop',
            name='where',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
