# Generated by Django 2.0.4 on 2018-05-06 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('soops', '0009_soop_where'),
    ]

    operations = [
        migrations.RenameField(
            model_name='soop',
            old_name='where',
            new_name='location',
        ),
    ]
