# Generated by Django 2.0.4 on 2018-06-09 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soops', '0010_auto_20180506_2027'),
    ]

    operations = [
        migrations.AddField(
            model_name='soop',
            name='num_vote_down',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='soop',
            name='num_vote_up',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='soop',
            name='vote_score',
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
