# Generated by Django 2.0.4 on 2018-08-23 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soops', '0011_auto_20180611_0144'),
    ]

    operations = [
        migrations.AddField(
            model_name='soop',
            name='score',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='soop',
            name='details',
            field=models.CharField(max_length=3000),
        ),
    ]
