# Generated by Django 2.0.4 on 2018-06-11 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('soops', '0011_auto_20180609_0536'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='soop',
            name='num_vote_down',
        ),
        migrations.RemoveField(
            model_name='soop',
            name='num_vote_up',
        ),
        migrations.RemoveField(
            model_name='soop',
            name='vote_score',
        ),
    ]
